apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  hostPath:
    path: /data/mongo
    type: DirectoryOrCreate
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
data:
  mongopassword: Y2hhbmRyYQ== #echo -n "chandra" | base64
  mongouser: YWRtaW51c2Vy #echo -n "adminuser" | base64
kind: Secret
metadata:
  name: mongo-init-creds
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP # no need to reach from outside
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
          # container port (app will be exposed at 27017)
          - containerPort: 27017
        args: ["--dbpath", "/data/db"]
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data-dir
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-init-creds
              key: mongouser
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-init-creds
              key: mongopassword
      volumes:
      - name: mongo-data-dir
        persistentVolumeClaim:
          claimName: "mongo-pvc"
  selector:
    matchLabels:
      app: mongodb