apiVersion: batch/v1
kind: CronJob
metadata:
  name: task-cronjob
spec:
 # run every min
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 3
      template:
        spec:
          containers:
          - name: task-app
            image: cbagade/task-app:v1
            command: ["python3", "app.py"]
          restartPolicy: Never

    # kubectl apply -f cron-job.yaml
    # will spawn job after 1 min
    # kubectl get jobs
    # kubectl get pods
    