apiVersion: v1
kind: Pod
metadata:
  name: task-app
  labels:
    app: task-app
spec:
  containers:
  - name: task-app
    image: cbagade/task-app:v1
    command: ["python3", "app.py"]
  restartPolicy: Always

  # kubectl apply -f pod.yaml
  # this pod is just printing whats there in app.py
  # its not running any continous application like flask
  # so it will print and will be in completed state, but kubernetes will try to bring it to running state
  # observe pod logs
  # and again it will crashloopbackof and then again will go in completed state
  # because there is not coninuous application running there
  # why kubernetes always start is by its property restartPolicy which is set to Always by default
  # try setting this to value Never and pod will be im completed state
  # 