apiVersion: v1
kind: Secret
metadata:
  name: mongo-data
  namespace: kube-learnings
# labels on secret
  labels:
    name: mongo-data
type: Opaque
data:
  MONGO_CLUSTER_NAME: 
  MONGO_PASSWORD: 
  MONGO_USERNAME: 

# Encoding is done like
# echo -n "chandra-dev" | base64
# Decoding
# echo -n "Y2hhbmRyYS1kZXY=" | base64 -d

