apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
  namespace: kube-learnings
  # labels on pod
  labels:
    name: secret-demo
spec:
  containers:
  - name: secret-demo
    image: cbagade/secret-demo:v1
    imagePullPolicy: Always
    envFrom:
    - secretRef:
        name: mongo-data
    


# docker build -t cbagade/secret-demo:v1 .
# docker push cbagade/secret-demo:v1

# create secret in imperative way
# kubectl create secret generic mongo-data --from-literal=MONGO_USERNAME=<user> --from-literal=MONGO_PASSWORD=<password> --from-literal=MONGO_CLUSTER_NAME=<cluster>
# verify secret
# kubectl get secret
# kubectl describe secret mongo-data
# kubectl get secret mongo-data -o yaml
# kubectl apply -f pod.yaml
# kubectl get pods -w
# kubectl expose --type=NodePort  pod  secret-demo --port 5000 --name secret-demo-svc

# post data
# curl --location 'http://localhost:32208/mongo/fruits' \
# --header 'Content-Type: application/json' \
# --data '{"fruitName":"Orange","from":"Tamilnadu","nutrients":"Vitamin B, Vitamin K","price":"200.50","organic":true,"description":"An avocado is a bright green fruit with a large pit and dark leathery skin. They'\''re also known as alligator pears or butter fruit. Avocados are a favorite of the produce section. They'\''re the go-to ingredient for guacamole dips."}'

# verify via get request
# curl 'http://localhost:32208/mongo/fruits'

# kubectl delete secret mongo-data
# kubectl delete -f pod.yaml
# create secret  in declarative way
# kubectl apply -f mongo_secret.yaml
# kubectl apply -f pod.yaml
# kubectl get pods -w
# no need to define service again
# curl localhost:<node port>/session

# post data (pl note change of fruitName)
# curl --location 'http://localhost:32208/mongo/fruits' \
# --header 'Content-Type: application/json' \
# --data '{"fruitName":"Apple","from":"Tamilnadu","nutrients":"Vitamin B, Vitamin K","price":"200.50","organic":true,"description":"An avocado is a bright green fruit with a large pit and dark leathery skin. They'\''re also known as alligator pears or butter fruit. Avocados are a favorite of the produce section. They'\''re the go-to ingredient for guacamole dips."}'

# verify via get request (should fetch you 2)
# curl 'http://localhost:32208/mongo/fruits'
 # kubectl delete -f pod.yaml