apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
  namespace: kube-learnings
  # labels on pod
  labels:
    name: secret-demo
spec:
  containers:
  - name: secret-demo
    image: cbagade/secret-demo:v1
    imagePullPolicy: Always
    env:
    - name: MONGO_USERNAME
      valueFrom:
        secretKeyRef:
          name: mongo-data
          key: MONGO_USERNAME
    - name: MONGO_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongo-data
          key: MONGO_PASSWORD
    - name: MONGO_CLUSTER_NAME
      valueFrom:
        secretKeyRef:
          name: mongo-data
          key: MONGO_CLUSTER_NAME
    



# verify secret
# kubectl get secret
# kubectl describe secret mongo-data

# kubectl delete -f pod.yaml
# kubectl apply -f pod_2.yaml
# kubectl get pods -w
# no need for service

# post data
# curl --location 'http://localhost:32208/mongo/fruits' \
# --header 'Content-Type: application/json' \
# --data '{"fruitName":"Avacado","from":"Tamilnadu","nutrients":"Vitamin B, Vitamin K","price":"200.50","organic":true,"description":"An avocado is a bright green fruit with a large pit and dark leathery skin. They'\''re also known as alligator pears or butter fruit. Avocados are a favorite of the produce section. They'\''re the go-to ingredient for guacamole dips."}'

# verify via get request (should fetch you 3)
# curl 'http://localhost:32208/mongo/fruits'

# kubectl delete -f mongo_secret.yaml
# kubectl delete -f pod_2.yaml
