apiVersion: apps/v1
# ReplicaSet is k8 artifact or k8 object
kind: DaemonSet
metadata:
  # name of RC
  name: first-app-rs
  labels:
    # another label
    type: front-end
spec:
  # template of pod to be created
  template:
    # pod metadata section
    metadata:
      name: first-app
      labels:
        tier: front-end
    # container specification
    spec:
      containers:
      - name: kube-first-app
        image: cbagade/pykubd-first-app:v5
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
  # pick pods from label
  selector: 
    matchLabels:
      tier: front-end


# kubectl apply -f daemon_set.yaml
# kubectl get pods -o wide
# kubectl delete -f daemon_set.yaml



