apiVersion: v1
# ResourceQuota is k8 artifact or k8 object
kind: ResourceQuota
metadata:
  # name of namespace
  name: compute-quota
  namespace: kube-learnings
spec:
  hard:
    pods: "100"
    requests.cpu: "8"
    requests.memory: 100Gi
    limits.cpu: "16"
    limits.memory: 200Gi    


# kubectl create -f namespace_resource_quota.yaml
# kubectl describe namespace kube-learnings 
