apiVersion: v1
# Pod is k8 artifact or k8 object
kind: Pod
metadata:
  # name of pod
  name: second-app
  # labels on pod
  labels:
    app: second-app
    tier: front-end
spec:
  # container specification. Pod will have container inside
  containers:
    # name of container
  - name: second-app-container
    # image of container
    image: cbagade/pykubd-first-app:v5
    imagePullPolicy: Always
    ports:
      # container port (app will be exposed at 5000)
      - containerPort: 5000

# docker build -t cbagade/pykubd-first-app:v5 .
# docker push cbagade/pykubd-first-app:v5
# kubectl apply -f pod.yaml
# kubectl get pods -w
# wait for pod to be in running state
# kubectl get pods -o wide
# curl http://<pod_ip_address>:5000/greetings

