# refer https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/
# will list all details of enclosing specs

apiVersion: v1
# Pod is k8 artifact or k8 object
kind: Pod
metadata:
  # name of pod
  name: second-app
  namespace: kube-learnings
  # labels on pod
  labels:
    app: second-app
    tier: front-end
spec:
  # container specification. Pod will have container inside
  containers:
    # name of container
  - name: second-app-container
    # image of container
    image: cbagade/pykubd-first-app:v5
    # Policy for pulling image 
    # Always pulled from image-registry
    # IfNotPresent - Only pulled when not present locally
    # Never - Get only locally (inside nodes) and if some issue with image, the container startup failed
    # Images inside Nodes are listed with crictl cli
    imagePullPolicy: Always
    ports:
      # container port (app will be exposed at 5000)
      - containerPort: 5000

# docker build -t cbagade/pykubd-first-app:v5 .
# docker push cbagade/pykubd-first-app:v5

# create namespace
# kubectl apply -f namespace.yaml

# create pod in that namespace
# kubectl apply -f pod_ns.yaml

# get all pods in kube-learnings namespace
# kubectl get pods -n kube-learnings -w

# get all pods in default namespace
# kubectl get pods

# set namespace
# kubectl config set-context $(kubectl config current-context) --namespace=kube-learnings

# view current namespace
# kubectl config view --minify | grep namespace

# get all namespaces
# kubectl get namespaces
