apiVersion: apps/v1
# ReplicaSet is k8 artifact or k8 object
kind: ReplicaSet
metadata:
  # name of RS
  name: first-app-rs
  labels:
    # another label
    type: front-end
spec:
  # template of pod to be created
  template:
    # pod metadata section
    metadata:
      name: first-app
      labels:
        tier: front-end
    # container specification
    spec:
      containers:
      - name: kube-first-app
        image: cbagade/pykubd-first-app:v5
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
  # number of pods to be created
  replicas: 3
  # pick pods from label
  selector: 
    matchLabels:
      tier: front-end


# kubectl apply -f replica_set.yaml
# kubectl get replicaset (or rs)
# kubectl get pods
# now try to create pod by pod.yaml (ensure label is same)
# since replica is 3, it will delete that pod immediately (rs also takes account of pods which are not created via rs but got matching labels)
# kubectl delete -f replica_set.yaml
# again
# kubectl apply -f pod.yaml
# kubectl apply -f replica_set.yaml
# total count will be 3
# kubectl delete -f pod.yaml
# kubectl delete -f replica_set.yaml


# Scaling
# kubectl apply -f replica_set.yaml
# change replicas in yaml and apply again
# also 
# kubectl scale --replicas=5 -f replica_set.yaml
# or
# kubectl scale --replicas=5 -f replicaset <replicaset_name>
# Last 2 ways of scaling won't make changes permenant on original yaml file
# One can scale based on load (advanced topic)
