apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-dep
spec:
  replicas: 3
  # this will decide how deployments should be updated
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: blue-green-app
    spec:
      containers:
      - name: blue-green-app
        image: cbagade/dep-up-app:v2
  selector:
    matchLabels:
      app: blue-green-app


