# refer https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/
# will list all details of enclosing specs

apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: frontend
    image: cbagade/pykubd-first-app:v5
    imagePullPolicy: Always
    ports:
      - containerPort: 5000
  tolerations:      
  - key: "app"
    operator: "Equal"
    value: "frontend"
    effect: "NoSchedule"
    

# kubectl get nodes
# kubectl taint node node01 key=value:effect
# Ex
# kubectl taint node node01 app=frontend:NoSchedule
# kubectl describe node node01 | grep -i taint
# There are 3 values of effect
# NoSchedule - If can't tolerate, new pod won't get schedule on node (but existing without toleration will keep running)
# PreferNoSchedule - Scheduler will try to not place pod on node which is not tolerating taint but not guarented
# NoExecute - New pods's won't get scheduled and existing pods, if any which do not tolerate will get evicted
# Check toleration section on pod yaml above
# kubectl apply -f pod.yaml
# kubectl get pods -o wide
# pod will be scheduled on node01 (or may not as node02 is not having any taint and this pod may placed there)
# kubectl delete -f pod.yaml

# untaint the node
# kubectl taint node node01 app=frontend:NoSchedule-

# observe taint on master node, so only system/k8 pods get scheduled on controlplane
# kubectl describe nodes controlplane | grep -i taint
# kubectl get pods -A | grep -i controlplane
