#version: "3.8"
services:
  mongodb:
    image: 'mongo:4.4.18'
    # named volume
    volumes:
      - data:/data/db
    #    environment: 
    #      MONGO_INITDB_ROOT_USERNAME: 'chandra'
    #      MONGO_INITDB_ROOT_PASSWORD: 'chandra'
    env_file:
      - ./env/mongo.env
# named volumes need to be listed
# no need to anonymous and bind volumes
volumes:
  data:

    # sudo rm /usr/local/bin/docker-compose
    # VERSION=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*\d')
    # DESTINATION=/usr/local/bin/docker-compose
    # sudo curl -L https://github.com/docker/compose/releases/download/${VERSION}/docker-compose-$(uname -s)-$(uname -m) -o $DESTINATION
    # sudo chmod 755 $DESTINATION

    # docker-compose up
    # will pull mongo image and will start container
    # also docker volume ls
    # in detached mode
    # docker-compose up -d
    # remove everything except volume
    # docker compose down
    # docker volume ls --> volume will be there
    # remove everything including volume
    # docker compose down -v
    # can demo by commenting/uncommenting env section
