apiVersion: v1
kind: Pod
metadata:
  name: cm-demo
  namespace: kube-learnings
  # labels on pod
  labels:
    name: cm-demo
spec:
  containers:
  - name: cm-demo
    image: cbagade/cm-demo:v1
    imagePullPolicy: Always
    env:
    - name: who_to_greet_ev
      valueFrom:
        configMapKeyRef:
          name: session-data
          key: who_to_greet_ev
    - name: session_ev
      valueFrom:
        configMapKeyRef:
          name: session-data
          key: session_ev
    - name: duration_ev
      valueFrom:
        configMapKeyRef:
          name: session-data
          key: duration_ev
    - name: topics_ev
      valueFrom:
        configMapKeyRef:
          name: session-data
          key: topics_ev


        
    


# docker build -t cbagade/cm-demo:v1 .
# docker push cbagade/cm-demo:v1

# kubectl delete -f pod.yaml
# kubectl delete -f cm.yaml
# kubectl apply -f cm.yaml
# kubectl apply -f pod_2.yaml
# kubectl get pods -w
# kubectl expose --type=NodePort  pod  cm-demo --port 5000 --name cm-demo-svc
# curl localhost:<node port>/session
# kubectl delete configmap session-data

# kubectl delete -f pod.yaml
# create config map in declarative way
# kubectl apply -f cm.yaml
# kubectl apply -f pod.yaml
# kubectl get pods -w
# no need to define service again
# curl localhost:<node port>/session
