apiVersion: v1
# Pod is k8 artifact or k8 object
kind: Pod
metadata:
  # name of pod
  name: sec-con-pod
  # labels on pod
  labels:
    app: sec-con-pod

spec:
  # container specification. Pod will have container inside
  containers:
    # name of container
  - name: sec-con-pod
    # image of container
    image: cbagade/pykubd-first-app:v5
    imagePullPolicy: Always
#    securityContext:
#      runAsNonRoot: true
#      runAsUser: 10000
    ports:
      # container port (app will be exposed at 5000)
      - containerPort: 5000

# kubectl apply  -f pod.yaml
# enter the pod
# kubectl exec -it sec-con-pod -- bash
# try to delete the pod
# rm -rf app.py
# kubectl delete  -f pod.yaml

# uncomment lines for security 
# repeat same exercise, this time you won't be able to