FROM ubuntu
ENTRYPOINT ["echo", "Hello"]
CMD ["World"]

# docker build -t cbagade/demo-cmdentry:v2 .
# docker push cbagade/demo-cmdentry:v2
# docker run cbagade/demo-cmdentry:v2
# docker run cbagade/demo-cmdentry:v2 'Dev Ops Team'
# docker run --entrypoint printf cbagade/demo-cmdentry:v2 'Dev Ops Team\n'