# this should be then used in all pods which required persistent volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  # requesting storage of 1Gi
  resources:
    requests: 
      storage: 1Gi