apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  # no need to reach from outside
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: cbagade/pykub-demo-auth:latest
        ports:
          # container port (app will be exposed at 80)
          - containerPort: 80        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: cbagade/pykub-demo-users-2:latest
        env:
        - name: AUTH_ADDRESS
          #value: "10.96.28.237"
          value: "auth-service.kube-learnings"
        ports:
          # container port (app will be exposed at 80)
          - containerPort: 5000          

# same image as auth from pod_internal demo
# cd user_api
# docker build -t cbagade/pykub-demo-users-2:latest .
# docker push cbagade/pykub-demo-users-2:latest
# look at users-app.js
# ${process.env.AUTH_SERVICE_SERVICE_HOST} is auto generated by kubernetes , can be used along with process.env.AUTH_ADDRESS
# DNS would be service name . namespace
# kubectl config view --minify | grep namespace:

# kubectl apply -f app_deployment.yaml
# kubectl exec -it <user_pod> -- /bin/bash
# look at env variables  and notice AUTH_SERVICE_SERVICE_HOST

# kubectl logs <pod> -f --> for both auth and users pod
# http://localhost:30005/signup 
# http://localhost:30005/signup/svc
# kubectl delete -f app_deployment.yaml