apiVersion: v1
kind: LimitRange
metadata:
  name: default-values-cpu
  namespace: kube-learnings
spec:
  limits:
  - default:
      cpu: 750m
      memory: 1Gi
    defaultRequest:
      cpu: 500m
      memory: 500Mi
    max:
      cpu: "2"
      memory: 2Gi
    min:
      cpu: 100m
      memory: 500Mi
    type: Container

  # These are default values for container resources , if not specified on pod
  # These are set at namespace level